// =================================================================================================
// Module:
//  GFX2U3D.cs
//
// Description:
//  Unity3D script for gaining access to the GestureFX 2 Unity3D plugin.
//
// Created:
//  July 10, 2015
//
// Author:
//  Dave Wilson
//
// Copyright:
//  2015, GestureTek Systems Inc.  All Rights Reserved.
// =================================================================================================

using UnityEngine;
using System.Collections;
using System;
using System.Runtime.InteropServices;


namespace GTek
{

  public class GFX2U3D
  {
    // =============================================================================================
    // Function:
    //  Connect
    //
    // Description:
    //  Attempts to open a connection to the GestureTek ScreenXtreme tracker.
    //
    // Returns:
    //  bool
    //    Returns true if a connection to the tracker is established.  Returns false if a connection
    //    could not be made.
    // =============================================================================================
    [DllImport("GFX2U3D")]
    public static extern bool Connect();


    // =============================================================================================
    // Function:
    //  Disconnect
    //
    // Description:
    //  Closes a previously opened connection to the GestureTek ScreenXtreme tracker.  If no 
    //  connection was previously opened, this function does nothing.
    // =============================================================================================
    [DllImport("GFX2U3D")]
    public static extern void Disconnect();


    // =============================================================================================
    // Function:
    //  IsConnected
    //
    // Description:
    //  Checks if a connection to the tracker has been established.
    // =============================================================================================
    [DllImport("GFX2U3D")]
    public static extern bool IsConnected();

    
    // =============================================================================================
    // Function:
    //  SetPointTransform
    //
    // Description:
    //  Sets the tranformation vector used to transform the points from screen space to world space
    //  in unity.
    //
    // Params:
    //  x, y
    //    The X and Y values will be multiplied against all of the points before being sent to Unity
    //  z
    //    The Z value will be used to set the Z value of all of the points.
    //  uHeight
    //    Height of the display, in pixels.  This will be used to flip the y coordinates before they
    //    are transformed as 0,0 in Unity is at the bottom left of the screen, not the top left.
    // =============================================================================================
    [DllImport("GFX2U3D")]
    public static extern void SetPointTransform(float x, float y, float z, UInt32 uHeight);


    // =============================================================================================
    // Function:
    //  GetPolygons
    //
    // Description:
    //  Retreives all of the polygons generated by the tracker for the last tracker frame.
    //
    // Params:
    //  pPoints (OUT)
    //    Array of points that will be filled with the points from the tracker.
    //  uMaxPts
    //    Maximum number of points that can be stored in pPoints.
    //  puPtsChanged (OUT)
    //    Indicates how many points were actually written to pPoints.
    //  pPolyCounts (OUT)
    //    Array of ints representing the number of points in each polygon
    //  uMaxPolys
    //    Maximum number of polygon counts that can be stored in pPolyCounts
    //  puPolysChanged (OUT)
    //    Changed to indicate the number of elements that were changed in pPolyCounts.
    //  uWaitMS
    //    How many milliseconds to wait for new data to arrive.
    //
    // Returns:
    //  bool
    //    Returns true if new tracker points were copied into pPoints and puPtsChanged was updated.
    //    Returns false if the number of points from the tracker exceeded the max size of pPoints or
    //    no new tracker points were available.  There can be the case where new data is available, 
    //    but there is no motion data (i.e. no one is interacting with the sysem).  In this case,
    //    puPtsChanged will be set to 0 and true will be returned.
    // =============================================================================================
    [DllImport("GFX2U3D")]
    public static extern bool GetPolygons
    (
      Vector3[]   pts,
      UInt32      uMaxPts,
      ref UInt32  puPtsChanged,
      int[]       polys,
      UInt32      uMaxPolys,
      ref UInt32  puPolysChanged,
      UInt32      uWaitMS
    );

  }

}; // namespace GTek


// =================================================================================================
// End of file
// =================================================================================================
